# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.provision :shell, path: "always.sh", run: "always"
end
