# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "forwarded_port", guest: 3030, host: 3030
  config.vm.network "forwarded_port", guest: 5432, host: 5432
  config.vm.provision "docker"
  config.vm.provision :shell, path: "bootstrap_production.sh"
  config.vm.provision :shell, path: "always.sh", run: "always"
end
