# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "boxcutter/ubuntu1604-desktop"
  config.vm.provision :shell, path: "developer.sh"
  config.vm.provision :shell, path: "always.sh", run: "always"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "template"
    vb.memory = "5120"
    vb.cpus = 2
  end  
end
